'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import Logo from '@/components/Logo'

interface VideoProject {
    id: string
    topic: string
    status: string
    duration: number
    createdAt: string
    series?: { name: string }
    queueItems: { status: string }[]
    finalVideos: { storageUrl: string }[]
}

export default function VideosPage() {
    const [projects, setProjects] = useState<VideoProject[]>([])
    const [loading, setLoading] = useState(true)

    const fetchVideos = async () => {
        const res = await fetch('/api/jobs')
        const data = await res.json()
        setProjects(data)
        setLoading(false)
    }

    useEffect(() => {
        fetchVideos()
        const interval = setInterval(fetchVideos, 10000)
        return () => clearInterval(interval)
    }, [])

    const completedVideos = projects.filter(p =>
        p.finalVideos.length > 0 || p.queueItems[0]?.status === 'complete' || p.status === 'ready'
    )
    const inProgress = projects.filter(p =>
        p.queueItems[0]?.status === 'pending' || p.queueItems[0]?.status === 'processing' || p.status === 'generating'
    )

    return (
        <div className="min-h-screen flex bg-[#09090b] text-[#fafafa]">
            <aside className="w-64 border-r border-white/5 flex flex-col p-6 shrink-0 bg-[#09090b]">
                <div className="mb-12">
                    <Logo size={36} showText={true} />
                </div>
                <nav className="flex flex-col gap-1 flex-1">
                    <SidebarLink href="/dashboard" label="Series Manager" />
                    <SidebarLink href="/dashboard/videos" label="All Episodes" active />
                    <SidebarLink href="/dashboard/settings" label="Settings" />
                </nav>
            </aside>

            <main className="flex-1 p-10 overflow-y-auto">
                <h1 className="text-3xl font-bold tracking-tight mb-2">All Episodes</h1>
                <p className="text-[#a1a1aa] text-sm mb-10">
                    Review and manage every video generated by your factory.
                </p>

                {/* In progress */}
                {inProgress.length > 0 && (
                    <section className="mb-12">
                        <h2 className="text-xs font-bold text-[#52525b] uppercase tracking-widest mb-6 flex items-center gap-2">
                            <div className="w-1.5 h-1.5 rounded-full bg-amber-500 animate-pulse" />
                            Production Queue
                        </h2>
                        <div className="flex flex-col gap-3">
                            {inProgress.map(p => (
                                <div key={p.id} className="p-5 rounded-2xl bg-white/[0.02] border border-white/5 flex items-center justify-between">
                                    <div className="flex items-center gap-4">
                                        <div className="w-10 h-10 rounded-xl bg-white/5 flex items-center justify-center">
                                            <div className="w-4 h-4 border-2 border-white/20 border-t-white rounded-full animate-spin" />
                                        </div>
                                        <div>
                                            <p className="text-sm font-bold">{p.topic}</p>
                                            <p className="text-[10px] text-[#52525b] uppercase font-black tracking-widest mt-1">
                                                {p.series?.name || 'Individual Video'} • {p.duration}s
                                            </p>
                                        </div>
                                    </div>
                                    <div className="flex items-center gap-6">
                                        <StatusBadge status={p.queueItems[0]?.status || p.status} />
                                        <ProgressIndicator duration={p.duration} createdAt={p.createdAt} />
                                    </div>
                                </div>
                            ))}
                        </div>
                    </section>
                )}

                {/* Completed */}
                <section>
                    <h2 className="text-xs font-bold text-[#52525b] uppercase tracking-widest mb-6">Mastered Tapes</h2>
                    {loading ? (
                        <div className="p-20 text-center glass-card border-dashed border border-white/5">
                            <p className="text-sm text-[#52525b]">Broadcasting signal...</p>
                        </div>
                    ) : completedVideos.length === 0 ? (
                        <div className="p-20 text-center glass-card border-dashed border border-white/5 rounded-3xl">
                            <p className="text-[#a1a1aa] mb-6">No episodes have been finalized yet.</p>
                            <Link href="/dashboard/generate" className="btn-primary">
                                Generate now
                            </Link>
                        </div>
                    ) : (
                        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">
                            {completedVideos.map(p => (
                                <Link key={p.id} href={`/dashboard/videos/${p.id}`} className="group p-4 bg-white/[0.02] border border-white/5 rounded-3xl hover:border-white/20 transition-all flex flex-col">
                                    <div className="w-full aspect-[9/16] max-h-56 rounded-2xl bg-black mb-4 flex items-center justify-center overflow-hidden border border-white/5 relative">
                                        {p.finalVideos[0]?.storageUrl ? (
                                            <video
                                                src={p.finalVideos[0].storageUrl}
                                                className="w-full h-full object-cover group-hover:scale-110 transition-transform duration-700"
                                                muted
                                                preload="metadata"
                                            />
                                        ) : (
                                            <span className="text-[10px] uppercase font-black tracking-[0.2em] text-[#52525b]">Awaiting Feed</span>
                                        )}
                                        <div className="absolute top-2 right-2 px-2 py-1 rounded-lg bg-black/60 backdrop-blur-md text-[10px] font-bold text-emerald-400 border border-emerald-500/20">
                                            READY
                                        </div>
                                    </div>
                                    <div className="px-2 pb-2">
                                        <p className="text-sm font-bold line-clamp-1 group-hover:text-blue-400 transition-colors uppercase italic tracking-tight">{p.topic}</p>
                                        <div className="flex items-center justify-between mt-3">
                                            <span className="text-[10px] text-[#52525b] font-black uppercase tracking-widest">
                                                {p.series?.name || 'NO SERIES'}
                                            </span>
                                            <span className="text-[10px] text-[#52525b] font-bold">
                                                {new Date(p.createdAt).toLocaleDateString()}
                                            </span>
                                        </div>
                                    </div>
                                </Link>
                            ))}
                        </div>
                    )}
                </section>
            </main>
        </div>
    )
}

function ProgressIndicator({ duration, createdAt }: { duration: number; createdAt: string }) {
    const estimatedMs = (duration === 30 ? 20 : 40) * 60 * 1000
    const elapsed = Date.now() - new Date(createdAt).getTime()
    const pct = Math.min(Math.round((elapsed / estimatedMs) * 100), 98)
    const remaining = Math.max(1, Math.ceil((estimatedMs - elapsed) / 60000))

    return (
        <div className="flex items-center gap-3">
            <div className="w-24 h-1 rounded-full bg-white/5 overflow-hidden">
                <div
                    className="h-full bg-blue-500 shadow-[0_0_8px_rgba(59,130,246,0.5)] transition-all duration-1000"
                    style={{ width: `${pct}%` }}
                />
            </div>
            <span className="text-[10px] font-bold text-[#52525b] uppercase tabular-nums">{remaining}m LEFT</span>
        </div>
    )
}

function StatusBadge({ status }: { status: string }) {
    const isError = status === 'failed'
    const isComplete = status === 'complete' || status === 'ready'

    return (
        <span className={`text-[10px] font-black uppercase tracking-widest px-2 py-0.5 rounded-md ${isError ? 'bg-rose-500/10 text-rose-500'
                : isComplete ? 'bg-emerald-500/10 text-emerald-500'
                    : 'bg-amber-500/10 text-amber-500'
            }`}>
            {status}
        </span>
    )
}

function SidebarLink({ href, label, active = false }: { href: string; label: string; active?: boolean }) {
    return (
        <Link
            href={href}
            className="px-3 py-2.5 rounded-xl text-sm font-medium transition-all"
            style={{
                background: active ? 'rgba(255,255,255,0.05)' : 'transparent',
                color: active ? '#fafafa' : '#a1a1aa',
            }}
        >
            {label}
        </Link>
    )
}
