import React from 'react';
import Link from 'next/link';
import Logo from '@/components/Logo';

export default function PrivacyPolicy() {
    return (
        <div className="min-h-screen bg-[#09090b] text-[#fafafa] font-sans selection:bg-blue-500/30">
            <header className="border-b border-white/5 bg-[#09090b]/80 backdrop-blur-xl sticky top-0 z-50">
                <div className="max-w-4xl mx-auto px-6 h-16 flex items-center justify-between">
                    <Link href="/">
                        <Logo size={32} />
                    </Link>
                    <Link href="/login" className="text-sm font-medium text-[#a1a1aa] hover:text-white transition-colors">
                        Back to Login
                    </Link>
                </div>
            </header>

            <main className="max-w-3xl mx-auto px-6 py-20 animate-fade-in">
                <h1 className="text-4xl font-bold mb-4 tracking-tight">Privacy Policy</h1>
                <p className="text-[#a1a1aa] mb-12">Last updated: March 8, 2026</p>

                <div className="space-y-12 prose prose-invert prose-blue max-w-none">
                    <section>
                        <h2 className="text-2xl font-semibold mb-4 text-white">1. Introduction</h2>
                        <p className="text-[#a1a1aa] leading-relaxed">
                            Janga ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, and safeguard your information when you use our video generation platform. By using Janga, you agree to the collection and use of information in accordance with this policy.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold mb-4 text-white">2. Information We Collect</h2>
                        <p className="text-[#a1a1aa] leading-relaxed mb-4">
                            We collect several types of information to provide and improve our service to you:
                        </p>
                        <ul className="list-disc pl-6 space-y-2 text-[#a1a1aa]">
                            <li><strong>Personal Identification:</strong> Name, email address, and profile picture provided through Google Authentication.</li>
                            <li><strong>Social Media Data:</strong> If you connect TikTok or YouTube accounts, we receive authentication tokens and basic profile information necessary to post content on your behalf.</li>
                            <li><strong>Content Data:</strong> Video project settings, topics, and the actual videos generated by our AI pipeline.</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold mb-4 text-white">3. How We Use Your Data</h2>
                        <ul className="list-disc pl-6 space-y-2 text-[#a1a1aa]">
                            <li>To create and manage your Janga account.</li>
                            <li>To process video generation jobs using our backend inference pipeline.</li>
                            <li>To publish generated videos to your connected social media accounts (TikTok, YouTube, Instagram) at your explicit request.</li>
                            <li>To provide customer support and notify you of project completions.</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold mb-4 text-white">4. Data Storage and Deletion</h2>
                        <p className="text-[#a1a1aa] leading-relaxed">
                            Videos generated on Janga are stored on secure cloud storage. For your privacy and security, <strong>generated videos are automatically deleted from our production storage after 24 hours</strong> of generation. We do not store your raw video files indefinitely.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold mb-4 text-white">5. Third-Party Services</h2>
                        <p className="text-[#a1a1aa] leading-relaxed">
                            Janga interacts with third-party APIs (Google/YouTube, TikTok, Instagram). Your use of these integrations is subject to their respective privacy policies:
                        </p>
                        <div className="mt-4 grid grid-cols-1 sm:grid-cols-2 gap-4">
                            <a href="https://policies.google.com/privacy" className="glass-card p-4 text-sm hover:border-blue-500/50 transition-colors">Google Privacy Policy</a>
                            <a href="https://www.tiktok.com/legal/privacy-policy" className="glass-card p-4 text-sm hover:border-purple-500/50 transition-colors">TikTok Privacy Policy</a>
                        </div>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold mb-4 text-white">6. Contact Us</h2>
                        <p className="text-zinc-400">
                            If you have any questions about this Privacy Policy, please contact us at: <strong>senyonam557@gmail.com</strong>
                        </p>
                    </section>
                </div>
            </main>

            <footer className="border-t border-white/5 py-12">
                <div className="max-w-4xl mx-auto px-6 text-center text-sm text-[#52525b]">
                    &copy; 2026 Janga. All rights reserved.
                </div>
            </footer>
        </div>
    );
}
